openapi: 3.0.1
info:
  title: '@jupiterone/graph-pingidentity'
  description: A JupiterOne Integration for ingesting data of the PingIdentity
  x-cortex-git:
    github:
      repository: JupiterOne/graph-pingidentity
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-pingidentity'
  x-cortex-service-groups:
    - tier-4
